### PR TITLE
refactored home controller, added a display all survey feature

### LINKED ISSUE #63: Display available surveys on the homepage

### PR DESCRIPTION
**Pull request by GiuseppePapalia**
created integration tests for it as well

image

### CODE REVIEW

**Review by JulianMendoza — CHANGES_REQUESTED** [review]
Please pull from master again, there are conflicts

**Comment by oyenmwen** [comment]
Looks really awesome

**Comment by oyenmwen** [comment]
Please resolve merge conflicts so it can be merged

**Review by JulianMendoza — APPROVED** [review]

**Review by oyenmwen — APPROVED** [review]
Good job dude 👍🏿

**Pull request merged**
