### PR TITLE
MongoDB 

### LINKED ISSUE #61: Use a NOSQL database (in accordance to our presentation topic)
SurveyMonkey will use MongoDB

### PR DESCRIPTION
**Pull request by oyenmwen**
Added  and configured project to use MongoDB as the database.

### CODE REVIEW

**Review by JulianMendoza — CHANGES_REQUESTED** [review]
Are the binary files necessary? Shouldn't the lib directory be in the gitignore? Other than that looks great.

**Comment by oyenmwen** [comment]
> Are the binary files necessary? Shouldn't the lib directory be in the gitignore? Other than that looks great.

Nope they are not necessary at all. But honestly too lazy to remove them 🥴

**Comment by oyenmwen** [comment]
> Are the binary files necessary? Shouldn't the lib directory be in the gitignore? Other than that looks great.

The .gitignore we have is standardized from from the java github/gitignore so I guess they are necessary 🤷🏿‍♂️. I'll add the maven gitingore as well and see

**Comment by GiuseppePapalia** [comment]
should remove all those jars before we put this through

**Comment by oyenmwen** [comment]
> should remove all those jars before we put this through

how can i go about doing this? It might be worth it to just add them their  > 500 KB

**Comment by GiuseppePapalia** [comment]
> > should remove all those jars before we put this through
> 
> how can i go about doing this? It might be worth it to just add them their > 500 KB

https://devconnected.com/how-to-remove-files-from-git-commit/

we want to get rid of smelly files

**Comment by oyenmwen** [comment]
> > > should remove all those jars before we put this through
> > 
> > 
> > how can i go about doing this? It might be worth it to just add them their > 500 KB
> 
> https://devconnected.com/how-to-remove-files-from-git-commit/
> 
> we want to get rid of smelly files

aight boss

**Review by GiuseppePapalia — APPROVED** [review]
looks good now

**Review by Tamiod — APPROVED** [review]
looks good

**Pull request merged**
