### PR TITLE
Julian dev

### PR DESCRIPTION
**Pull request by JulianMendoza**
Posting survey now works you can view your survey JSON at 
/testQuestions?title=
Post form might be a bit buggy please report any noticeable bugs.

### CODE REVIEW

**Review by oyenmwen — COMMENTED** [review]
It all looks very good but:

1.  What is the purpose of the helper classes ?
2.  How about the corresponding tests

**Comment by loisaleghe** [comment]
if possible be adding comments to your code to make reviewing it easier

**Comment by Tamiod** [comment]
This looks good. Just missing corresponding tests

**Review by Tamiod — COMMENTED** [review]
This is fine.
Comments will make this more reader friendly.

**Pull request merged**
