### PR TITLE
created wrapper and helper class to help connect controller to storeAnswer.js file and added surveyCode to attributes in json

### LINKED ISSUE #28: Storing user's answers with specific question
retrieve user's answers and add them to respective question when a user submits their answers to survey

### PR DESCRIPTION
**Pull request by loisaleghe**
storing answers from users to specific repository using surveycode and getting question for specific answer using question id

### CODE REVIEW

**Review by JulianMendoza — APPROVED** [review]
Great work!

**Review by GiuseppePapalia — COMMENTED** [review]
you should consider removing console logging and print statements when merging to master

**Comment by loisaleghe** [comment]
> you should consider removing console logging and print statements when merging to master

definitely i would do that and maybe send another pull request?

**Comment by GiuseppePapalia** [comment]
> > you should consider removing console logging and print statements when merging to master
> 
> definitely i would do that and maybe send another pull request?

you can amend this request

**Comment by loisaleghe** [comment]
> > > you should consider removing console logging and print statements when merging to master
> > 
> > 
> > definitely i would do that and maybe send another pull request?
> 
> you can amend this request

okay that makes sense, thank you

**Pull request merged**
