### PR TITLE
Justice dev

### LINKED ISSUE #21: Survey Confirmation Page
thanks for entering your survey... your code is ... send this link to your friends

### PR DESCRIPTION
**Pull request by oyenmwen**
Implemented the Survey successfully created/confirmation page. Closes #21 and implemented the show survey page (Issue #22). Histogram Questions are currently not populated. Also did some bootstrap styling

### CODE REVIEW

**Review by JulianMendoza — APPROVED** [review]
Awesome work, a bit inconsistent with the white spacing but no big deal. Great job!

**Comment by oyenmwen** [comment]
> Awesome work, a bit inconsistent with the white spacing but no big deal. Great job!

Okay will watch out for that next time. Thanks

**Review by Tamiod — APPROVED** [review]
Looks good. Adding comments will make it even better.

**Comment by oyenmwen** [comment]
> Looks good. Adding comments will make it even better.

okay thanks will be sure to do that next time

**Pull request merged**
